### ISSUE TITLE
Error when deploying edge functions in v.1.54.6

### ISSUE THREAD

**Issue by Jonny1987** [supabase/edge-runtime#378]
# Bug report

- [x] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

I get this error when deploying edge functions using `supabase functions deploy --no-verify-jwt` in my CI (My CI config file code has not changed):

```
Status: Downloaded newer image for ghcr.io/supabase/edge-runtime:v1.54.6
failed to start docker container: Error response from daemon: failed to create task for container: failed to initialize logging driver: dial tcp 127.0.0.1:54328: connect: connection refused
```

The last time my CI run this is was successful and was using image v1.54.2

My github actions yaml file is:

```
name: Deploy to Production

on:
  workflow_dispatch:
  # Allows external webhook trigger
  repository_dispatch:
    types:
      - webhook

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
      SUPABASE_DB_PASSWORD: ${{ secrets.SUPABASE_PRODUCTION_DB_PASSWORD }}
      SUPABASE_PROJECT_ID: ${{ secrets.SUPABASE_PRODUCTION_PROJECT_ID }}

    steps:
      - name: Clone repository
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Install supabase cli
        uses: supabase/setup-cli@v1
        with:
          version: latest

      - name: Link supabase project
        run: supabase link --project-ref $SUPABASE_PROJECT_ID

      - name: Deploy supabase functions
        run: supabase functions deploy --no-verify-jwt

      - name: Push supabase migrations
        run: supabase db push
```

## To Reproduce

Deploy edge function with `supabase functions deploy --no-verify-jwt`

## Expected behavior

Function should be deployed

## System information

Using github actions
edge-runtime v1.54.6
